### ISSUE TITLE
Dealing with multiple `init()`

### ISSUE THREAD

**Issue by ghigt** [beego/beedoc#110]
How do you deal with multiple `init` functions to register a model?

In the example [here](http://beego.me/docs/mvc/model/orm.md), you take the example of `model.go` and `main.go` there is a problem.
Indeed, the `init()` function of the `main.go` is called before `model.go`.

So if I call `orm.RunCommand()` in the `init()`, we can see that the models are not registered.

**Comment by nanohard** [comment]
I think I solved that by doing the following, but after I couldn't get beego/orm to create a table with new values using --force=1 (cache problem somewhere?) I switched to gorm and no longer use this:

filename: models.go
```
package models

import (
    "github.com/astaxie/beego/orm"
)

func init() {
    orm.RegisterModel(new(User))  // defined in package:models, file:user.go
    db.AutoMigrate(&User{})  // "db" looks wrong here. I don't know what I had.
}
```

filename: main.go
```
package main

import (
    "github.com/astaxie/beego"
    "github.com/astaxie/beego/orm"
    _ "github.com/go-sql-driver/mysql"

    _ "test/beegotest/models"  // just link it? I forget.
    _ "test/beegotest/routers"
)

func init() {
    orm.RegisterDriver("mysql", orm.DRMySQL)
    orm.RegisterDataBase("default", "mysql", "user:password@/dbname?charset=utf8")
    if err != nil {
        panic(err)
    }

    orm.RunCommand()
}

func main() {
	beego.Run()
}
```

I just realized how old this question was, but I already typed it. And I had the same question too, so posting.
