### ISSUE TITLE
关于beego的log库

### ISSUE THREAD

**Issue by mitiger** [beego/beedoc#183]
最近才使用log库，发现在windows操作系统系下有问题，
logger.SetLogger("file", `{"filename":"`+filename+`" , "maxdays": `+strconv.Itoa(maxdays)+`}`)
这里的filename 在windows 下，文件不会自动创建，而且有目录的情况，好像也创建不成功

不知道这块在windows下要怎么去做？

**Comment by lei-cao** [comment]
hi @mitiger , sorry for the late reply. If the issue still exists, please fire a issue in http://github.com/astaxie/beego repo.
closing this issue.
