### ISSUE TITLE
GOPATH 没设置

### ISSUE THREAD

**Issue by LengBinBin** [beego/beedoc#200]
执行
`go get github.com/beego/bee `
`go get github.com/astaxie/beego`
报错
`package github.com/beego/bee: cannot download, $GOPATH not set. For more details see: go help gopath`
怎么设置GOPATH？

**Comment by astaxie** [comment]
https://github.com/astaxie/build-web-application-with-golang/blob/master/zh/preface.md

先学习一下Go基础吧

**Comment by LengBinBin** [comment]
OK 谢了， 就找这两句
