### ISSUE TITLE
What is SNDA CND system?

### ISSUE THREAD

**Issue by shinriyo** [beego/beedoc#216]
In the document,
https://github.com/beego/beedoc/blob/master/en-US/faq/FAQ.md

I found the text "SNDA CND system"
I googled. I guess that CND is "Contents Delivery Network".
And, I found SNDA the China site. (http://www.snda.com/)
So, is it means that SNDA's CND system?

**Comment by astaxie** [comment]
yea, that's a typo. should be  SNDA's CDN system

**Comment by lei-cao** [comment]
clothing issue.
