### ISSUE TITLE
Russian translate for left sidebar menu on beego.me

### ISSUE THREAD

**Issue by Smile42RU** [beego/beedoc#231]
Hi @astaxie, how we can translate left menu on beego.me website? Thanks.

For example:
Beego introduction -> Введение в Beego
Contributing -> Разработка Beego
Release Notes -> Список изменений
Upgrade Guide -> Инструкция по обновлению

Install / Upgrade -> Установка / Обновление
Bee tool usage -> Использование инструмента Bee (or: Инструмент Bee)

Quickstart -> Быстрый старт
Create new project -> Создать новый проект (or: Новый проект)
Routing setting -> Настройки роутинга
Controller -> Контроллер
Models -> Модели
View -> Представление
Static files -> Файлы статики
Modules -> Модули

In this section i have two proposal: first variant it's translate to natural language, but i think second proposal looks like most preference because Session, Cache and others it's modules names and i think not right to translate it:

Session Module -> Модуль сессий (or: Модуль Session)
Cache Module -> Модуль кэша (or: Модуль Cache)
Logs Module -> Модуль логов (or: Модуль Logs)
Httplib Module -> Модуль Httplib
Context Module -> Модуль контекста (or: Модуль Context)
Toolbox Module  -> Модуль Toolbox
Config Module -> Модуль конфигурации (or: Модуль Config)
i18n Module -> Модуль переводов (or: Модуль i18n)

Advanced Beego -> Продвинутый Beego
Live Monitor -> Live-монитор
Automated API Document -> Автоматическая документация для API

Deployment -> Процесс релиза
Stand alone Deploy -> Релиз самостоятельного приложения
Deploy with Supervisord -> Релиз с Supervisord
Deploy with nginx -> Релиз с nginx
Deploy with Apache -> Релиз с apache

Middleware contribution -> (I've skip it, because i don't know how translate it right. I'll provide something about this menu item some later)

Demos -> Демки
Chat Room -> Чат
URL Shortener -> Сокращатель ссылок
Todo List -> Список задач
FAQ -> FAQ (it's normal)

**Comment by astaxie** [comment]
@Smile42RU Thanks for your translation. just do as your proposal. if it can't translate just leave it as the english. like the Session and Cache in chinese I also leave the english name

**Comment by lei-cao** [comment]
closing this ticket
