### ISSUE TITLE
 build output "docs" already exists and is a directory

### ISSUE THREAD

**Issue by xrain0610** [beego/beedoc#317]
按照官方命令 运行 
第一开启应用内文档开关，在配置文件中设置：EnableDocs = true,
第二步就是使用bee generate docs生成docs文件，
然后在你的main.go函数中引入_ "beeapi/docs"。
这样你就已经内置了docs在你的API应用中，然后你就使用bee run watchall true,让我们的API应用跑起来，同时第四个参数true表示每次自动化的build文档，
现在我们就要看我们的API文档了，你可以打开另一个命令窗口执行bee run docs -isDownload=true然后就会自动的下载swagger文档查看器，同时运行在了8089端口，你也可以使用bee run docs -docport=8888修改相应地端口。

运行 bee run docs -isDownload=true 
报错如下：
>2015/11/16 18:18:50 [INFO] Uses 'docs' as 'appname'
>2015/11/16 18:18:50 [INFO] Initializing watcher...
>2015/11/16 18:18:50 [TRAC] Directory(/Users/xRain/Documents/GoLang/Projects/src/api.simcu.com/controllers)
>2015/11/16 18:18:50 [TRAC] Directory(/Users/xRain/Documents/GoLang/Projects/src/api.simcu.com)
>2015/11/16 18:18:50 [TRAC] Directory(/Users/xRain/Documents/GoLang/Projects/src/api.simcu.com/models)
>2015/11/16 18:18:50 [TRAC] Directory(/Users/xRain/Documents/GoLang/Projects/src/api.simcu.com/routers)
>2015/11/16 18:18:50 [TRAC] Directory(/Users/xRain/Documents/GoLang/Projects/src/api.simcu.com/tests)
>2015/11/16 18:18:50 [INFO] Start building...
>go install api.simcu.com: build output "docs" already exists and is a directory
>2015/11/16 18:18:51 [ERRO] ============== Build failed ===================

**Comment by jiangbing9293** [comment]
我是通过在工程目录下 执行 bee generate docs 生成docs.go解决问题的 ，希望能帮到你

**Comment by lei-cao** [comment]
hi @xrain0610 you are using `bee run docs` which will trying to create the compiled output file named `docs` which is an existing directory already. 
If you want to generate docs, the easiest way to use it is `bee run -gendoc=true`
