### ISSUE TITLE
Docs messed up in chrome

### ISSUE THREAD

**Issue by jamieomatthews** [beego/beedoc#335]
Not sure exactly why this is happening, but certain docs get messed up in chrome.  Seconds after load they swap to a sort of unformatted text

![screen shot 2016-01-16 at 8 13 56 pm](https://cloud.githubusercontent.com/assets/1930819/12375927/bc12e498-bc8d-11e5-835f-a66ebe485bde.png)

**Comment by jamieomatthews** [comment]
Works fine in firefox btw.  Chrome version Version 47.0.2526.106 (64-bit) OSX El Capitan

**Comment by astaxie** [comment]
works on my chrome. Version 47.0.2526.111 (64-bit) OS X EI Captian
