### ISSUE TITLE
unknown bee test command

### ISSUE THREAD

**Issue by lizhenghui** [beego/beedoc#356]
lizh@FX-JSJ522 MINGW64 /e/git/code/go/src/goapi/tests (test)
$ bee version
bee   :1.4.1
beego :1.6.0
Go    :go version go1.5rc1 windows/amd64

lizh@FX-JSJ522 MINGW64 /e/git/code/go/src/goapi/tests (test)
$ bee test goapi
bee: unknown subcommand "test"
Run 'bee help' for usage.

**Comment by lei-cao** [comment]
duplicated https://github.com/beego/beedoc/issues/341
