### ISSUE TITLE
参数配置那一章里有一个小错误?

### ISSUE THREAD

**Issue by AG3** [beego/beedoc#369]
> EnableHTTPS
> 
> 是否启用 HTTPS，默认是 false 关闭。当需要启用时，先设置 EnableHTTPListen = false，并设置HTTPSCertFile 和 HTTPSKeyFile
> 
> beego.BConfig.Listen.EnableHTTPS = false
> 

其中EnableHTTPListen应为EnableHTTP

**Comment by astaxie** [comment]
@lei-cao please fix it

**Comment by lei-cao** [comment]
updated https://github.com/beego/beedoc/commit/b4b1f7c91dfae75bdfd71899df9f3b8b88e4acf1

**Comment by lei-cao** [comment]
https://github.com/beego/beedoc/pull/371
