### ISSUE TITLE
session 控制部分的文档是不是该更新了？

### ISSUE THREAD

**Issue by mstmdev** [beego/beedoc#373]
[session 控制](https://github.com/beego/beedoc/blob/master/zh-CN/mvc/controller/session.md)中beego.SessionProvider、beego.SessionSavePath等参数是不是已经废弃了，配置文件对应的参数似乎也发生了变化（sessionsavepath变成了sessionproviderconfig？？），请确认一下是不是该更新相关的文档了。

**Comment by astaxie** [comment]
@lei-cao please check it

**Comment by luodaihong** [comment]
同楼主.Session的文档确实要更新了,我那会学的时候就走了弯路.

**Comment by kangkang66** [comment]
是的.浪费了我一天时间~卧槽
新版配置
`beego.BConfig.WebConfig.Session.SessionOn=true
	beego.BConfig.WebConfig.Session.SessionProvider="file"
	beego.BConfig.WebConfig.Session.SessionProviderConfig="./tmp"
	beego.BConfig.WebConfig.Session.SessionName="beegocookie"`
