### ISSUE TITLE
提一个小小的建议，beego.AutoRouter  是否可以优化下下

### ISSUE THREAD

**Issue by fireflyhoo** [beego/beedoc#374]
```
beego.Router("/admin/category", &admin.CategoryController{})
beego.AutoRouter(&admin.CategoryController{})
```

我的本意是  CategoryController  匹配 /admin/category ，
其他的方法 匹配 /admin/category/add ,/admin/category/del  等等。现在的情况是
其他的方法匹配的是 /category/add，/category/del
尝试过注解，但是感觉略微麻烦，时候可以把 beego.AutoRouter(&admin.CategoryController{}) 该写成

beego.AutoRouter("/admin/"&admin.CategoryController{}) 或者其他更方便的方式

**Comment by DennisMao** [comment]
@fireflyhoo  可以使用Mapping,已支持
