### ISSUE TITLE
讲真，对于初学者，用着心累。又变没了。

### ISSUE THREAD

**Issue by Genffy** [beego/beedoc#380]
routers/router.go:34: undefined: beego.NSHandler

[http://beego.me/docs/mvc/controller/router.md#namespace](namespace)

**Comment by astaxie** [comment]
不好意思，这个函数后来改写的时候忘记了，内置应该是有的，我已经加上了 https://github.com/astaxie/beego/commit/22196d78415fff13189bffc387c2545f4d9bf377
