### ISSUE TITLE
is it bug? router not working with '_'  是不是BUG？路由加个下划线不起作用。

### ISSUE THREAD

**Issue by brucewoods** [beego/beedoc#511]
beego.Router("/q/_:keyword", &controllers.SearchController{})

**Comment by brucewoods** [comment]
2016/08/31 21:34:40 [router.go:855] [D] | 404 |     432.29µs| nomatch|  GET     /q/_8549++66++6

**Comment by astaxie** [comment]
please move the beego issue to github.com/astaxie/beego
