### ISSUE TITLE
orm自动建表 字符表非utf8

### ISSUE THREAD

**Issue by h22f** [beego/beedoc#561]
dsn := dbUser + ":" + dbPassword + "@tcp(" + dbHost + ":" + dbPort + ")/" + dbName + "?charset=utf8"
err := orm.RunSyncdb("default", false, true)

已配置连接为utf8但是创建的表字符为:cp1252 West 
手动修改表字符集为utf8  插入数据库中文乱码. 
请问要如何解决?

**Comment by xiaomingzhong** [comment]
同问

**Comment by xiye518** [comment]
问题已找到，是个人mysql字符集编码格式没设置的原因，可参考https://www.jianshu.com/p/90f751ea37d1

**Comment by xiye518** [comment]
本人遇到的是orm自动建表存的数据，然后字符串乱码，数据库设置后就没这个原因了，
