### ISSUE TITLE
自动化文档

### ISSUE THREAD

**Issue by jakeywu** [beego/beedoc#571]
在生成自动化文档环节, 无需在main.go 函数中引入 _ "beeapi/docs"　且docs哪里来的也不造啊

**Comment by astaxie** [comment]
恩，beego1.7版本升级到了swagger之后已经不需要docs了

**Comment by xiaomingzhong** [comment]
我生成的文档和 https://beego.me/docs/advantage/docs.md 不一样 是我哪里配置错了吗

**Comment by xiaomingzhong** [comment]
我在controllers中增加了接口，但是文档（http://127.0.0.1/swagger/index.html）出来的还是老页面，没法更新到最新的，需要配置什么吗？还是运行命令有问题（bee run spd -gendoc=true -downdoc=true）
