### ISSUE TITLE
AppConfigPath is Deprecated

### ISSUE THREAD

**Issue by thetlinthu** [beego/beedoc#573]
Referring to the documentation:

https://github.com/beego/beedoc/blob/master/en-US/mvc/controller/config.md

> AppConfigPath
> 
> Application configuration file path. It is conf/app.conf by default. You can change it to your own file.
> 
> beego.AppConfigPath = "conf/app2.conf"
> AppConfigProvider
> 
> File format of AppConfig, default is ini. Could be xml, yaml, json as well.
> 
> beego.AppConfigProvider = "ini"

If you check inside `beego/config.go` , the capital `A` is now small `a` for `appConfigPath` which means its private and not public.

It looks like now, the correct method to do this is as follows:

```
import "github.com/astaxie/beego"

func main() {
    beego.LoadAppConfig("ini", "your/favorite/path/app.conf")
    beego.Run()
}
```

Is this correct? If so, I can provide a quick pull request to fix the docs. Thanks for the help.

**Comment by ever-cifuentes-globant** [comment]
Any update on this? I will need support for yml config files.

**Comment by DennisMao** [comment]
Fixed
