### ISSUE TITLE
API自动化文档->应用注释->@Title 没有生效

### ISSUE THREAD

**Issue by LittleRobotRoad** [beego/beedoc#576]
![image](https://cloud.githubusercontent.com/assets/13929310/25731144/4364d7e0-3176-11e7-9277-97441b0f01ca.png)

**Comment by astaxie** [comment]
![image](https://cloud.githubusercontent.com/assets/233907/25803618/5676e09c-342a-11e7-9be5-aa31f5aec4d1.png)

**Comment by LittleRobotRoad** [comment]
![image](https://cloud.githubusercontent.com/assets/13929310/25812029/9b9478a2-3447-11e7-8072-65bc538053c2.png)

![image](https://cloud.githubusercontent.com/assets/13929310/25812012/8bcd7a04-3447-11e7-86dc-e27eb032f13c.png)
![image](https://cloud.githubusercontent.com/assets/13929310/25812024/9434a7da-3447-11e7-8d74-ececba6a2aab.png)
是我没描述详细，我在注释那写了@Title了的

**Comment by astaxie** [comment]
function的title已经当做OperationID处理了
