### ISSUE TITLE
How to get the RequestBodyIndo

### ISSUE THREAD

**Issue by dncmn** [beego/beedoc#584]
func (this *ObjectController) Post() {
    var ob models.Object
    json.Unmarshal(this.Ctx.Input.RequestBody, &ob)
    objectid := models.AddOne(ob)
    this.Data["json"] = "{\"ObjectId\":\"" + objectid + "\"}"
    this.ServeJSON()
}

What's the  models.Object and the AddOne()????

**Comment by DennisMao** [comment]
1.models https://beego.me/docs/mvc/model/models.md#model-definition 
2.AddOne is a private method of the models Object.
You can get more information from the above link.
