### ISSUE TITLE
How to build a docs site for my own project like http://beego.me/docs?

### ISSUE THREAD

**Issue by hsluoyz** [beego/beedoc#605]
Hi,

I like the theme of http://beego.me/docs very much and I would like to use it as the docs site of my own project hosted in GitHub. But this repo only contains the contents, it doesn't mention how it is built, or what tool is used.

I know GitHub Pages uses Jekyll to generate static sites. But this repo seems not using Jekyll. May I ask how to build such a docs site for my own project? Is it also free or open-source?

BTW, it will be better if I can know how the whole http://beego.me/ site is built.

**Comment by astaxie** [comment]
@hsluoyz We use https://github.com/beego/beeweb to setup the beego website and this docs auto render in web. You can use it you like

**Comment by hsluoyz** [comment]
Thanks, beeweb is just what I am looking for :)
