### ISSUE TITLE
beego有没有在线的api文档

### ISSUE THREAD

**Issue by deqoder** [beego/beedoc#618]
试过那个自动生成文档，但执行bee run -downdoc=true -gendoc=true时，0004 ERROR Failed to generate the docs, 也没说怎么个fail.

官方的文档好像只是泛泛而谈，没有哪个函数有什么类型参数，返回又是什么这样的说明。

**Comment by memstone** [comment]
我也遇到这个问题，后来更新了一下 bee 工具，结果连 -docgen 的参数也没了。
现在只能翻源码么？
没有 API 查询，实在不方便啊。

**Comment by xiaomingzhong** [comment]
我运行项目时( bee run -gendoc=true -downdoc=true )
然后生成了文档，但是进入页面 http://127.0.0.1/swagger/#!/customer
只有一下两个选项，
swagger.json
swagger.yml
和 https://beego.me/docs/advantage/docs.md 这里的文档不一样，是哪里配置错了吗

**Comment by deqoder** [comment]
@memstone 我现在会了，其实go语言自带godocserver, 打开后，除了标准库，放在src下的go get下来的项目的文档都有了（其实只是把源码里的注释抽成了，不过确实很方便，还可以很方便地直接看源码）
