### ISSUE TITLE
文档编码规范问题

### ISSUE THREAD

**Issue by gaojiyong** [beego/beedoc#638]
https://beego.me/docs/mvc/model/rawsql.md

此处是不是应该是 := 呢,很多地方都是这样我看
![image](https://user-images.githubusercontent.com/11253729/31485888-ff7a6fd4-af67-11e7-989c-3c72e06c0319.png)

**Comment by DennisMao** [comment]
https://github.com/beego/beedoc/pull/694   已修正，谢谢支持
