### ISSUE TITLE
【UPDATE】ListenTCP4 已经修改成bool类型，原来文档上还是字符串类型

### ISSUE THREAD

**Issue by forging2012** [beego/beedoc#646]
https://github.com/beego/beedoc/search?utf8=✓&q=ListenTCP4+&type=

ListenTCP4

监听本地网络地址类型，默认为 "tcp4"，该值可以是 "tcp", "tcp4", "tcp6", "unix" or "unixpacket" 之一。

beego.BConfig.Listen.ListenTCP4 = "tcp4"

**Comment by astaxie** [comment]
fixed
