### ISSUE TITLE
Beego 如何做到支持Protobuffer？同时能够自动根据struct逆向生成proto文件吗？

### ISSUE THREAD

**Issue by CBDlkl** [beego/beedoc#671]
工作环境中，遇到传输数据需要用`protobuf协议`，那么若是我想用Beego的话得解决如下几个问题：
1.  框架级支持Protobuffer的序列与反序列化。
2. 最好能够根据定义好的Struct来逆向生成proto文件，因为编写好的proto文件生成的go实体，并没有可读性。

如上是目前需要解决的两个地方，我翻阅过其他很多go项目，目前并没有很好的解决方案。不知道beego是否能够提供类似的解决方案。

**Comment by lwhile** [comment]
不知道你用 Protobuf 原因是不是用了 gRPC，如果是的话你应该意识到 Beego 只是一个 HTTP 协议层面上的框架。

如果不是的话，针对第一个问题，引入一个protobuf的工具库就好了。

针对第二个问题， 可以参考下 StackOverflow 上的这个回答 ：https://stackoverflow.com/questions/38724556/generate-proto-file-from-golang-struct

然后这个项目是 beedoc 而不是 beego。我得先关闭掉这个 issue，需要继续讨论的话请移步 https://github.com/astaxie/beego/issues 重新发起 issue

**Comment by lwhile** [comment]
#688
