### ISSUE TITLE
logs包输出日志信息不完善

### ISSUE THREAD

**Issue by yingyan003** [beego/beedoc#673]
![image](https://user-images.githubusercontent.com/30212457/34936503-9e0f5dae-fa1c-11e7-8691-e24ca1615dc6.png)
如图所示，使用logs.Error（）打印出来的错误行数是42行（42行是该函数的上层调用处），但实际打印该错误的真实位置（如图中的110行）并没有在日志中显示出来，这样非常不利于快速地定位错误。

**Comment by lwhile** [comment]
#688
