### ISSUE TITLE
task文档问题反馈

### ISSUE THREAD

**Issue by wuzehv** [beego/beedoc#892]
作者你好，[task文档](https://github.com/beego/beedoc/blob/master/en-US/module/task.md)反馈个小问题：

```go
tk1 := task.NewTask("tk1", "0 12 * * * *", func() error {
	fmt.Println("tk1")
	return nil
})
```

这里的第三个参数是TaskFunc类型的，需要一个参数。

顺便请教一下，在调用`task.NewTask`的时候第一个参数已经设置了`TaskName`，为什么在后面`task.AddTask("tk1", tk1)`的第一个参数不直接取结构体`Task.Taskname`呢？日常使用中，每个task通常都会用不同的名字。

**Comment by flycash** [comment]
感谢。

**Comment by flycash** [comment]
欢迎以后继续反馈问题，同时更加欢迎发PR来帮我们修复完善文档。
