### ISSUE TITLE
orm能不能支持分表功能

### ISSUE THREAD

**Issue by dangwan** [beego/beedoc#920]
对于大数据量的表，一般都会进行分表处理。表名为 前缀+数字序号，目前beego的orm中，orm.RegisterModel(new(Order)) 注册的模型只能对应一个表名。 orm.Insert(&order) 也不能动态切换表名。不知道有没有计划显式的支持下呢

**Comment by flycash** [comment]
这是个大问题。之前我们讨论过是否支持。目前来看，分库分表功能是一个非常困难的功能，并不是简单支持一个表名后缀就可以。比如说，在支持分库分表的情况下，我们需要考虑聚合函数，排序之类的该如何实现。

如果你只是单纯需要后缀表名字，你可以尝试一下实现TableName的接口：
```go
func (m MyTbale) TableName() string {
	return "my_table" + m.Id % 16;
}
```
按照我的理解，这应该可以了。

**Comment by dangwan** [comment]
> 这是个大问题。之前我们讨论过是否支持。目前来看，分库分表功能是一个非常困难的功能，并不是简单支持一个表名后缀就可以。比如说，在支持分库分表的情况下，我们需要考虑聚合函数，排序之类的该如何实现。
> 
> 如果你只是单纯需要后缀表名字，你可以尝试一下实现TableName的接口：
> 
> ```go
> func (m MyTbale) TableName() string {
> 	return "my_table" + m.Id % 16;
> }
> ```
> 
> 按照我的理解，这应该可以了。

那我只能自己来实现分表功能了，正如你说的，切表名字确实容易实现，关键还是聚合、搜索、排序这些功能

**Comment by flycash** [comment]
感谢理解。如果你打算开源或者找到了好用的开源项目，不妨在这留个连接，我们其实意识到golang上，分库分表的中间件，并不如java那般齐全，功能稳定。
