### ISSUE TITLE
core/logs/log_msg.go  OldStyleFormat()  有点问题希望修复一下

### ISSUE THREAD

**Issue by Akllen** [beego/beedoc#933]
![image](https://user-images.githubusercontent.com/19727048/120200412-e29f5180-c256-11eb-89cc-85bfa5d5371f.png)
这里面 字符串格式化之后赋值给了lm.Msg  但是下文里面都是使用msg

**Comment by flycash** [comment]
这个问题在master 分支上已经修复了
