### ISSUE TITLE
文档中的 github.com/beego/beego/v2/session/mysql 似乎不是一个有效的地址

### ISSUE THREAD

**Issue by nexmoe** [beego/beedoc#945]
https://beego.me/docs/mvc/controller/session.md

<img width="695" alt="Snipaste_2021-10-08_21-39-10" src="https://user-images.githubusercontent.com/16796652/136567179-d7c9b4bb-75d2-4aa7-8fbb-064a3e1647a1.png">

报错如下
```
go get: module github.com/beego/beego/v2@upgrade found (v2.0.1), but does not contain package 
github.com/beego/beego/v2/session/mysql
```

**Comment by flycash** [comment]
确实是错的。可以帮我们修正一下。不过正确的是`github.com/beego/beego/v2/server/web/session/mysql`
