### ISSUE TITLE
自动化文档注册路由404

### ISSUE THREAD

**Issue by zhang3woshi** [beego/beedoc#955]
![image](https://user-images.githubusercontent.com/103362702/167750909-67bdee78-acaf-4ee1-ae74-9713448bf24b.png)
![image](https://user-images.githubusercontent.com/103362702/167750929-3cee835b-dbb5-4a7a-b104-dd64bc8df315.png)
通过自动化文档方式注册路由以及controller实现见上图，注册路径为/v1/plugin/upload，调用接口报404.
![image](https://user-images.githubusercontent.com/103362702/167751096-76002ef4-b46b-4b88-9bbb-adbe574eaa55.png)
![image](https://user-images.githubusercontent.com/103362702/167751116-4d2e0282-d3fb-411b-8f4d-4f0191bfed57.png)

**Comment by xiaohuasheng** [comment]
我也遇到了，自动生成项目的时候，老哥你解决了吗？

**Comment by mei2015** [comment]
可尝试删除 routers 下面的 commentsRouter_controllers 文件再次运行 bee run

**Comment by qq635938204** [comment]
> 可尝试删除 routers 下面的 commentsRouter_controllers 文件再次运行 bee run

删除commentsRouter_controllers 后，再次运行bee run -gendoc=true没有重新生成该文件，目录结构如下图
![image](https://user-images.githubusercontent.com/8327799/176804941-3d47f104-f900-4c74-ac65-b1dd89aaa7f0.png)
![image](https://user-images.githubusercontent.com/8327799/176804994-d106bbaf-b3a4-454b-a17a-367610710dfb.png)

**Comment by flycash** [comment]
在新版本里面，bee run 移除了自动生成 comment_router 的功能，取而代之使用了 bee generate router 的命令。
而且，这里面有一个误会，就是 -gendoc 并不是用来生成 comment_router 的。有没有这个，在早期都会生成 comment_router
