### ISSUE TITLE
建议开发文档里面的方法描述增加标题点击后跳转到源码查看页面

### ISSUE THREAD

**Issue by mrcuix** [beego/beedoc#96]
建议开发文档里面的方法描述增加标题点击后跳转到源码查看页面，具体如：

Prepare() [查看](https://gowalker.org/github.com/astaxie/beego#Controller_Prepare)

```
这个函数主要是为了用户扩展用的，这个函数会在下面定义的这些 Method 方法之前执行，用户可以重写这个函数实现类似用户验证之类。
```

或者:
[Prepare()](https://gowalker.org/github.com/astaxie/beego#Controller_Prepare)

```
这个函数主要是为了用户扩展用的，这个函数会在下面定义的这些 Method 方法之前执行，用户可以重写这个函数实现类似用户验证之类。
```

**Comment by DennisMao** [comment]
Accepted
